name: Releases
on:
  push:
    tags:
      - "v*"
jobs:
  build:
    name: Build Go
    strategy:
      matrix:
        os:
          - ubuntu-latest
        arch:
          - amd64
        include:
          - os: ubuntu-latest
            goos: linux
            node: 14
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Build Vue project
        run: |
          cd web
          npm install
          npm run build
          mkdir static
          if [ "${{ matrix.os }}" = "windows-latest" ]; then
            echo windows-latest
            xcopy /E /I dist\* ..\static\
          else
            echo ubuntu-latest
          fi
          mv dist/ ../static
          cd ..

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21.1

      - name: Build Go Project
        run: go build -o dbland-${{ matrix.goos }}-${{ matrix.arch }}

      - name: Compress files
        run: |
          if [ "${{ matrix.os }}" = "windows-latest" ]; then
            7z a release.zip static dbland-${{ matrix.goos }}-${{ matrix.arch }} config.yaml README.md README_CN.md
          else
            tar -czvf dbland-${{ matrix.goos }}-${{ matrix.arch }}.tar.gz static dbland-${{ matrix.goos }}-${{ matrix.arch }} config.yaml README.md README_CN.md
          fi

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: dbland-${{ matrix.goos }}-${{ matrix.arch }}.tar.gz