name: Releases
on:
  push:
    branches: [ dev ]
jobs:
  build:
    name: Build Go
    strategy:
      matrix:
        os:
          - ubuntu-latest
        arch:
          - amd64
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Build Vue project
        run: |
          cd web
          npm install
          npm run build
          mkdir static
          if [ "${{ matrix.os }}" = "windows-latest" ]; then
            echo windows-latest
            xcopy /E /I dist\* ..\static\
          else
            echo ubuntu-latest
            mv dist/ ../static
          fi
          echo matrix
          cd ..

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21.1

      - name: Build Go Project
        run: go build -o dbland-${{ matrix.os }}-${{ matrix.arch }}

      - name: Compress files
        run: |
          ls
          if [ "${{ matrix.os }}" = "windows-latest" ]; then
            7z a release.zip static dbland-${{ matrix.os }}-${{ matrix.arch }} config.yaml README.md README_CN.md
          else
            tar -czvf release.tar.gz static dbland-${{ matrix.os }}-${{ matrix.arch }} config.yaml README.md README_CN.md
          fi

      - name: Upload Release Assets
        uses: actions/upload-release-asset@v1
        with:
          asset_path: release.tar.gz
          asset_name: dbland-${{ matrix.os }}-${{ matrix.arch }}.tar.gz
          asset_content_type: application/gzip
          release-tag: ${{ github.ref }}
          github_token: ${{ secrets.GITHUB_TOKEN }}