name: Build and Release
on:
  create:
    tags:
      - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21.1

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Build Vue project
        run: |
          cd web
          npm install
          npm run build
          mkdir static
          cp -R dist/* static/
          cd ../

      - name: Build for Linux (amd64)
        run: GOOS=linux GOARCH=amd64 go build -o dbland-linux-amd64

      - name: Build for Linux (arm64)
        run: GOOS=linux GOARCH=arm64 go build -o dbland-linux-arm64

      - name: Build for macOS (amd64)
        run: GOOS=darwin GOARCH=amd64 go build -o dbland-darwin-amd64

      - name: Build for macOS (arm64)
        run: GOOS=darwin GOARCH=arm64 go build -o dbland-darwin-arm64

      - name: Build for Windows (amd64)
        run: GOOS=windows GOARCH=amd64 go build -o dbland-windows-amd64.exe

      - name: Build for Windows (arm64)
        run: GOOS=windows GOARCH=arm64 go build -o dbland-windows-arm64.exe

      - name: Create Linux tar.gz (amd64)
        run: tar -czf dbland-linux-amd64.tar.gz dbland-linux-amd64

      - name: Create Linux tar.gz (arm64)
        run: tar -czf dbland-linux-arm64.tar.gz dbland-linux-arm64

      - name: Create macOS tar.gz (amd64)
        run: tar -czf dbland-darwin-amd64.tar.gz dbland-darwin-amd64

      - name: Create macOS tar.gz (arm64)
        run: tar -czf dbland-darwin-arm64.tar.gz dbland-darwin-arm64

      - name: Create Windows zip (amd64)
        run: zip -r dbland-windows-amd64.zip dbland-windows-amd64.exe

      - name: Create Windows zip (arm64)
        run: zip -r dbland-windows-arm64.zip dbland-windows-arm64.exe

      - name: Upload Release Assets
        uses: actions/upload-release-asset@v1
        with:
          asset-path: |
            dbland-linux-amd64.tar.gz
            dbland-linux-arm64.tar.gz
            dbland-darwin-amd64.tar.gz
            dbland-darwin-arm64.tar.gz
            dbland-windows-amd64.zip
            dbland-windows-arm64.zip
          release-tag: ${{ github.ref }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
