name: Releases
on:
  push:
    tags:
      - "v*"
jobs:
  build:
    name: Build Go
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        arch: [amd64, arm64]
        include:
          - os: ubuntu-latest
            goos: linux
            node: 14
            go-version: 1.21.1
          - os: macos-latest
            goos: darwin
            node: 14
            go-version: 1.21.1

    runs-on: ${{ matrix.os }}
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Build Vue project
        run: |
          cd web
          npm install
          npm run build
          mkdir static
          if [ "${{ matrix.os }}" = "windows-latest" ]; then
            echo windows-latest
            xcopy dist\* ..\static\ /E /I /Y
          else
            echo ubuntu-latest
            mv dist/ ../static
          fi
          cd ..

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Build Go Project
        run: |
          if [ "${{ matrix.os }}" = "windows-latest" ]; then
            go build -o dbland.exe .
          else
            go build -o dbland .
          fi
      - name: Compress files
        run: |
          if [ "${{ matrix.os }}" = "windows-latest" ]; then
            $sourceFiles = "dbland.exe", "config.yaml", "README.md", "README_CN.md"
            $zipFile = "dbland-${{ matrix.goos }}-${{ matrix.arch }}.zip"
            Add-Type -A 'System.IO.Compression.FileSystem'
            [System.IO.Compression.ZipFile]::CreateFromDirectory($PWD, $zipFile, $null, $false)
            Write-Host "Files compressed successfully!"
          else
            tar -czvf dbland-${{ matrix.goos }}-${{ matrix.arch }}.tar.gz dbland config.yaml README.md README_CN.md
          fi

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: dbland-${{ matrix.goos }}-${{ matrix.arch }}.tar.gz
          allowUpdates: true